spring:
  application:
    name: shiro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.180.2.26:3306/shiro-demo?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: "123456"
server:
  port: 8080

#mybatis的相关配置
mybatis:
  #mapper配置文件位置
  mapper-locations: classpath:mapper/*.xml
  #配置xml文件中resultType返回值的包位置
  type-aliases-package: com.cheetah.shiro.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true




